config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'admin/home' => 'admin#home'

  resources :leads
  

 root 'pages#index'
 get 'services' => 'pages#services'
 get 'contact'=>'pages#contact'
 get 'thanks'=>'pages#thanks'
  get 'new-patient'=>'pages#new-patient'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/lead.rb
class Lead < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_admin! 
  def home
  end
   def index
    @leads = Lead.all
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to '/thanks', notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:first_name, :last_name, :phone, :email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to '/thanks', notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:first_name, :last_name, :phone, :email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def contact
		@lead=Lead.new

		
end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/home.html.erb
<%= render 'layouts/notification'%>
<center><h1>Welcome to the Dashboard</h1>

</center>

app/views/layouts/_notification.html.erb
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Natural Therapeutics Atlanta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//load.sumome.com/" data-sumo-site-id="eb8440cb83084e47be3b2fac036679b48e2a45b892fb5d1ff0f6c90bf623da0a" async="async"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Natural Therapeutics Atlanta</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
   <ul class="nav navbar-nav navbar-right">
     <% if admin_signed_in? %>
        <li><%=link_to 'Home',  admin_home_path %></li>
        <li><%=link_to 'Leads',  leads_path %></li>
        <li><%=link_to 'Sign Out',  destroy_admin_session_path, method: :delete %></li>
    <%else%>
        <li><a href="/">Home</a></li>
        <li><a href="http://atlgentlechiro.wordpress.com/">Blog</a></li>
        <li><a href="/services">Learn</a></li>
        <li><a href="/new-patient">New Patient</a></li>
        <li><a href="/contact">Contact Us</a></li>
    <%end%>
     </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  


<%= yield %>

</body>



  
</html>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit 'Send', class: 'button' %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<%= render 'layouts/notification'%>
<h1>Editing Lead</h1>

<%= render 'leads/form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<%= render 'layouts/notification'%>
<center><p id="notice"><%= notice %></p>

<h1>Listing Leads</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.first_name %></td>
        <td><%= lead.last_name %></td>
        <td><%= lead.phone %></td>
        <td><%= lead.email %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lead', new_lead_path %>
</center>

app/views/leads/new.html.erb
<center><h1>Contact Us</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>
</center>

app/views/leads/show.html.erb
<%= render 'layouts/notification'%>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @lead.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @lead.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lead.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>

app/views/pages/contact.html.erb
<center>
<h1> Contact Us</h1>
</center>
<br><br><br>
<div class = 'container col-md-6 rt'>
<center>


<%= form_for(@lead) do |f| %>

        <div class="field">
          <%= f.label :first_name %><br>
          <%= f.text_field :first_name %>
        </div>
    
                <br><br>
    
        <div class="field">
          <%= f.label :last_name %><br>
          <%= f.text_field :last_name %>
        </div>
    
                <br><br>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div><br><br>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div><br><br>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div><br><br>
  <div class="actions">
    <%= f.submit 'Send', class: 'button' %>
  </div><br><br>
<% end %>
</div>

</center>
<div class='contianer col-md-6 lt'>

<p class ='t'> Call: <b> (404) 724-5424</b><br><br>Email: <b>naturaltherapeuticsatl@gmail.com</b></p>
  </div>

app/views/pages/index.html.erb
<div class="thebackground">
<h1 class='headertextmain'> Welcome to Natural Therapeutics Atlanta</h1><br></br>
<center><a href ="/services"><button class="button"> Learn More </button></a></center>
</div>

app/views/pages/new-patient.html.erb
<center>
<h1> Coming Soon! </h1>
</center>

app/views/pages/services.html.erb
<center>

<h1 class="headertext"> Services </h1>
<br><br>
<h2> Welcome to Natural Therapeutics Atlanta </h2>
<br>
<p class='tn'>We offer:</p>
	<br>
			<div class="t"><b>∙ Blood Nutrition, Allergy Testing, etc.</b></div><br>
			<div class="t"><b>∙ Hormone Testing</b></div><br>
			<div class="t"><b>∙ Weight Loss</b>: Not starving Yourself - Lose Up to 80lbs</div><br>
			<div class="t"><b>∙ Chiropractic</b>: without popping and cracking your spine</div><br>
			<div class="t"><b>∙ Electro-Acupuncture</b>: Acupuncture to stop smoking.</div>


<br><br>

<p class='tn'>Contact us to receive a <b>FREE</b> consult.</p>
<br></br>
<center>
<a href="/contact"><button class='button2'> Receive Your FREE Consult </button></a>
</div></center>

app/views/pages/thanks.html.erb
<center><p id="thanks"> Thanks, We'll Be In touch shortly</p>
<br><br><br>
<h3> Where to go next? </h3>
</br>
<%= link_to "Learn About Our Treatments ->", '/services'%>

</center>